
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_NANO_SOC_LT24_NIOS(

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_SCK,
	output		          		ADC_SDI,
	input 		          		ADC_SDO,

	//////////// ARDUINO //////////
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// GPIO_0, GPIO connect to LT24 - 2.4" LCD and Touch //////////
	input 		          		LT24_ADC_BUSY,
	output		          		LT24_ADC_CS_N,
	output		          		LT24_ADC_DCLK,
	output		          		LT24_ADC_DIN,
	input 		          		LT24_ADC_DOUT,
	input 		          		LT24_ADC_PENIRQ_N,
	output		          		LT24_CS_N,
	output		    [15:0]		LT24_D,
	output		          		LT24_LCD_ON,
	output		          		LT24_RD_N,
	output		          		LT24_RESET_N,
	output		          		LT24_RS,
	output		          		LT24_WR_N
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

assign LT24_LCD_ON = 1'b1; //default on


//=======================================================
//  Structural coding
//=======================================================

 lt24_qsys u0 (
	  .clk_clk            (FPGA_CLK1_50),            //         clk.clk
	  .reset_reset_n      (1'b1),      //       reset.reset_n
	  .key_external_connection_export                  (KEY),                    //                   key_external_connection.export
	  .lcd_reset_n_export                              (LT24_RESET_N), // lcd_reset_n.export
	  ////touch panel interface
	  .touch_panel_spi_external_MISO                    (LT24_ADC_DOUT),                    //                  touch_panel_spi_external.MISO
	  .touch_panel_spi_external_MOSI                    (LT24_ADC_DIN),                    //                                          .MOSI
	  .touch_panel_spi_external_SCLK                    (LT24_ADC_DCLK),                    //                                          .SCLK
	  .touch_panel_spi_external_SS_n                    (LT24_ADC_CS_N),                    //                                          .SS_n
	  .touch_panel_pen_irq_n_external_connection_export (LT24_ADC_PENIRQ_N), // touch_panel_pen_irq_n_external_connection.export
	  .touch_panel_busy_external_connection_export      (LT24_ADC_BUSY),       //      touch_panel_busy_external_connection.export
     .lt24_controller_0_conduit_end_cs                 (LT24_CS_N ),                 //                                          .cs
     .lt24_controller_0_conduit_end_rs                 (LT24_RS ),                 //                                          .rs
     .lt24_controller_0_conduit_end_rd                 (LT24_RD_N ),                 //                                          .rd
     .lt24_controller_0_conduit_end_wr                 (LT24_WR_N),                 //                                          .wr
     .lt24_controller_0_conduit_end_data               (LT24_D )               //                                          .data

 );
 

endmodule
